#!/usr/bin/env bash
set -euo pipefail

test -f AGENTS.md
test "$(cat CLAUDE.md)" = "@AGENTS.md"
test -f .github/copilot-instructions.md
test -f docs/language-spec.md
test -f SECURITY.md

if rg -n 'Co-Authored-By|Signed-off-by|generated by (AI|ChatGPT|Claude|Codex)' \
  --glob '!scripts/check-repo.sh' .; then
  echo "Prohibited authorship attribution found." >&2
  exit 1
fi

echo "Repository checks passed."
